### ISSUE TITLE
Getting Scanned Results

### ISSUE THREAD

**Issue by WambuaSimon** [BlinkID/blinkid-android#115]
I am using the demo APK which i have obtained by running the Cloned project from your site.  After scanning an ID card, the details are populated dynamically on the ResultActivity class.  However, I cant figure out a way to extract each field independently from the scanned results.  
My problem is in the snippet below:

case RECOGNIZER_BUNDLE:
                mRecognizersWithResult = new ArrayList<>();
                mRecognizerBundle.loadFromIntent(intent);
                for ( Recognizer< Recognizer, Recognizer.Result > r : mRecognizerBundle.getRecognizers() ) {
                    if ( r.getResult().getResultState() != Recognizer.Result.State.Empty ) {
                        mRecognizersWithResult.add( r );
                      //  Toast.makeText(this, "Data\n"+r.getResult(), Toast.LENGTH_LONG).show();

                    }
                }
r.getResult() is not returning the scanned fields like Primary ID, Secondary ID, Date of birth...etc despite the fact that these fields are being populated dynamically in the application

**Comment by DoDoENT** [comment]
Hello!

To better get acquainted with the BlinkID API, I suggest starting with the [minimum sample app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-aMinimalSample) as it shows how you can obtain Result object from specific Recognizer object and then obtain specific fields from that Result object.

The [all recognizers sample](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID_AllRecognizersSample) shows which recognizers are available within the BlinkID SDK and how you can use them. In order to simplify the ResultActivity, it delegates its data from result extraction procedure to [result extractor](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/LibUtils/src/main/java/com/microblink/result/ResultFragment.java#L53) which is implemented [for each and every recognizer](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/LibUtils/src/main/java/com/microblink/result/extract) in the SDK and shows how specific fields can be obtained from specific result object.

**Comment by MarishkaKravchenko** [comment]
for ( Recognizer< Recognizer, Recognizer.Result > r : recognizerBundle.getRecognizers() ) {
                if ( r.getResult().getResultState() != Recognizer.Result.State.Empty ) {
                    if(r.getResult() instanceof MrtdRecognizer.Result) {
                        MrtdRecognizer.Result recognizer = (MrtdRecognizer.Result) r.getResult();
                        ScanResult result = new ScanResult.ScanResultBuilder()
                                .setName(recognizer.getMrzResult().getPrimaryId())
                                .setLastName(recognizer.getMrzResult().getSecondaryId())
                    }
                }
            }

**Comment by dhruvi1kosmos** [comment]
@WambuaSimon have u got any solution ? how can I  extract  field  from the UsdlCombinedRecognizer scanned results?
