### ISSUE TITLE
DocumentFaceRecognizer return image upside down

### ISSUE THREAD

**Issue by rsimikic** [BlinkID/blinkid-android#153]
Hi,
I'm trying to extract document face along with pdf 417. For some reason 1/3 document face detection returns flipped image (upside down). Is it better approach if I configure two independent recognition instead of combining them into one bundle? 

Recognizer initialization:
```
documentFaceRecognizer = new DocumentFaceRecognizer();
documentFaceRecognizer.setReturnFullDocumentImage(true);
documentFaceRecognizer.setDetectorType(DocumentFaceDetectorType.IDENTITY_CARD_TD1);
documentFaceRecognizer.setFullDocumentImageDpi(300);

successFrameGrabberRecognizer = new SuccessFrameGrabberRecognizer(pdf417Recognizer);

recognizerBundle = new RecognizerBundle(successFrameGrabberRecognizer, documentFaceRecognizer);
```

Obtaining results:
```
if (pdf417State == Recognizer.Result.State.Empty) {
    pdf417State = pdf417Recognizer.getResult().getResultState();
    pdf417Result = pdf417Recognizer.getResult().clone();

    successFrameGrabberResult = successFrameGrabberRecognizer.getResult().clone();
}

if (detectorState == Recognizer.Result.State.Empty) {
    detectorState = documentFaceRecognizer.getResult().getResultState();
    documentFaceResult = documentFaceRecognizer.getResult().clone();
}

if (pdf417State == Recognizer.Result.State.Empty || 
    detectorState == Recognizer.Result.State.Empty) {
    return null;
}

Image successFrame = successFrameGrabberResult.getSuccessFrame();
if (successFrame != null) {
    Bitmap fsuccessFrameBitmap = successFrame.convertToBitmap();
}

Image fullDocumentImage = documentFaceResult.getFullDocumentImage();
if (detectedImage != null) {
     Bitmap fullDocumentBitmap = detectedImage.convertToBitmap();
   }
}
```

### Environment Details

**BlinkID version:** 4.8

**Device model:** S9

**Device Android version:** 9.0

**Comment by i1E** [comment]
Hi @rsimikic,

the problem is in our internal face detection algorithm which sometimes fails to detect face correctly (detects it upside down). We will try to do something to fix that for the next SDK release.

**Comment by rsimikic** [comment]
Hi @i1E ,
Thanks for you answer. What about my second question: 

> Is it better approach if I configure two independent recognition instead of combining them into one bundle?

**Comment by i1E** [comment]
Hi @rsimikic,

it depends on the use-case. In your case, if you want that user is able to scan pdf417 barcode and document with face at the same time, you have to activate both recognizers.

It is always better to activate as few recognizers as possible at the same time, because recognition will be faster. If you are implementing your [custom scan activity](https://github.com/BlinkID/blinkid-android#-embedding-recognizerrunnerview-into-custom-scan-activity), then you can also reconfigure recognizers during recognition by using [RecognizerRunnerView.reconfigureRecognizers](https://blinkid.github.io/blinkid-android/com/microblink/view/recognition/RecognizerRunnerView.html#reconfigureRecognizers-com.microblink.entities.recognizers.RecognizerBundle-) method.

**Comment by Brankacro** [comment]
Hello @rsimikic,

We are closing this as this is inactive. If you have any questions please reopen it.
Also, feel free to contact us directly at support@microblink.com
Best regards.
