### ISSUE TITLE
MrtdRecognizer.Result getFullDocumentImage() not returning image

### ISSUE THREAD

**Issue by soso199** [BlinkID/blinkid-android#159]
I have set
recognizer.setReturnFullDocumentImage(true);

**Comment by culoi** [comment]
Hello @soso199 

Please check our [ImagesSample demo app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-ImagesSample) to see how we set returning of the [FullDocumentImage](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L47-L62)

Please let us know how this works for you.

Regards

**Comment by soso199** [comment]
I tried this sample but it crashes ,  it isn't returning image

IllegalStateException: Data cannot be saved to intent because its size exceeds intent limit!

**Comment by culoi** [comment]
Hello @soso199 

This usually happens when you use Recognizer that produces an image or similar large object inside its Result and that object exceeds the Android intent transaction limit. You should enable different intent data transfer mode. 
You have to use optimised way for transferring RecognizerBundle between activities, while ensuring
that data does not get lost when Android restarts the scanning activity.

Please set theData transfer as below:

MicroblinkSDK.setIntentDataTransferMode(IntentDataTransferMode.PERSISTED_OPTIMISED);

Regards

**Comment by soso199** [comment]
Thanks , it worked
