### ISSUE TITLE
Adding a Image Listener to ScanCard activity causes it to not function in Android version 4.4.2 or 5.1

### ISSUE THREAD

**Issue by darkfoxdx** [BlinkID/blinkid-android#16]
I tried adding an image listener to the ScanCard activity to capture MyKad and it didn't do so on Android version 5.1 to 4.4.2. There is also no crash log or any log info as far as I can see. Even use the sample MyImageListener given in the documentation doesn't work. This is only for BlinkId 3.1.0. Apparently it works in one Android 4.4.2 when I lowered the version to BlinkId 3.0.0.

**Comment by i1E** [comment]
Hi @darkfoxdx,

you should be able to obtain MyKad images in BlinkID 3.1.0 because in latest version we have only added additional option to return face image. Please try [BlinkIDImageListenerDemo](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDImageListenerDemo) app. It scans MRTDs (Machine Readable Travel Documents) and stores the document images to SD card (`myImages` folder) but you can modify [these lines in MainActivity](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDDemo/BlinkIDImageListenerDemo/src/main/java/com/microblink/blinkid/MainActivity.java#L61-L69) and try scanning MyKad. 
Here is the code:

```java
...
    // create settings for MyKad recognizer
    MyKadRecognizerSettings myKad = new MyKadRecognizerSettings();
    // set to true to obtain face images
    myKad.setShowFaceImage(true);
    // set to true to obtain images containing full document
    myKad.setShowFullDocument(true);

    // set array of recognizers that will be used
    settings.setRecognizerSettingsArray(new RecognizerSettings[]{myKad});
...
```

If this demo app works for you, modify your code according to the example. Please let us know if you have managed to solve the issue.

**Comment by DoDoENT** [comment]
Hi @darkfoxdx,

please check if issue still persists in [v3.2.0](https://github.com/BlinkID/blinkid-android/releases/tag/v3.2.0).

If the issue is solved, please close it.

**Comment by darkfoxdx** [comment]
Oops, wanted to say it is resolved
