### ISSUE TITLE
United Arab Emirates ID scan not working in Oneplus 7 Pro Android device

### ISSUE THREAD

**Issue by rajubhusani** [BlinkID/blinkid-android#165]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description
United Arab Emirates ID scan not working in Oneplus 7 Pro Android device. Not able to scan the id.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:** : 4.9.1

**Device model:**: One Plus 7 Pro

**Device Android version:** 9.x

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by i1E** [comment]
Hi @rajubhusani,

this issue has already been fixed in our codebase, fix will be available for you in the new SDK release (v4.10.0) which is planned for the next week.

**Comment by rajubhusani** [comment]
Hi Team,

Appreciated for the quick update.

I have couple queries:
1) In Nokia 7 Plus device also we are facing same issue. Is that also be taken care in the next release? If yes it is cool. And I would like to know whether this issue is with the specific device or with the OS version? I mean I would like to know the technicality of the bug.

2) Right now we are using Blink ID UI wrapper library for Emirates ID scan with the Demo License key.  And I can see there is a logo of BlinkID on the camera surface view. Is this can be hidden when we use the production license? or do we need to do make any API call to hide? Please suggest.

**Comment by i1E** [comment]
Hi @rajubhusani,

1. For each device, our SDK chooses the best possible resolution, and for some devices with specific resolutions, we had a problem in the recognition. This issue is specific for some devices, we don't know each device that was affected, but probably the same problem was on Nokia 7 Plus. Please give us feedback, after you test the new version on that device, because we don't have it at the office.

2. This logo is present only when you are using test license key. When you get the production license key, logo will be automatically hidden. You don't need to do anything about that in the integration code.

**Comment by rajubhusani** [comment]
Thank you for the updates. I will close this ticket..
