### ISSUE TITLE
Is there support for the USDL scan with front camera.If we tried with sample app,it saying without auto focus the feature won't work

### ISSUE THREAD

**Issue by techvedikasolutions** [BlinkID/blinkid-android#167]
Hi,
Is there support for the USDL scan with front camera.If we tried with sample app,it saying without auto focus the feature won't work.Please let us know if there is any way to work with it.We really wanted the USDL scan feature with front camera only.

Thank you.

**Comment by i1E** [comment]
Hi @techvedikasolutions,

which sample app you are using for testing?

Actually, UsdlRecognizer require camera with autofocus only if "null quiet zone" is allowed, if you disable it by using [UsdlRecognizer.setNullQuietZoneAllowed(false)](https://docs.google.com/spreadsheets/d/1FFeiIGx447J5A7WuRO4SxdN6ZlqkpouFDEkOFx2reF0/edit#gid=48644150) then you will be able to scan the barcode.

But take note that scanning might not work on cameras without autofocus, because USDLs usually contain high density barcodes and sharp image of the barcode is required for data extraction.

**Comment by Brankacro** [comment]
Hello @techvedikasolutions,

We wanted to check if you need any assistance from our side. In case of any questions, please let us know. You can also contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @techvedikasolutions 

As this issue is inactive we will close it. In case of any questions, feel free to contact us. As said earlier, you can also contact us directly at support@microblink.com We will gladly assist you.

Best regards.
