### ISSUE TITLE
Replacement for DocumentDetector in Version 5.0

### ISSUE THREAD

**Issue by ckang777** [BlinkID/blinkid-android#186]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

I've used DocumentDetector to create a custom document scanner. Used it to capture
back image of the US driver license. However, in version 5 DocumentDetector is no longer available. What would be the substitute?

### Environment Details

**BlinkID version:**
5.0

**Comment by mparadina** [comment]
Hello @ckang777 

The BlinkID SDK available on GitHub is the “light” version that only includes the following recognizers: https://github.com/BlinkID/blinkid-android#-list-of-available-recognizers 
In order to obtain the full version that have all the recognizers available (amongst them is the DocumentDetector) please contact us at support@microblink.com.

Kind regards,
Milan

**Comment by Brankacro** [comment]
Hello @ckang777 

We are closing this as this is inactive. Please let us know in case of any additional questions.
Also, you can always contact us directly at support@microblink.com
We will gladly resolve all your questions and doubts.

Best regards.
