### ISSUE TITLE
Can't open camera with Device that only back facing camera

### ISSUE THREAD

**Issue by Rina2001** [BlinkID/blinkid-android#200]
Hello team, 
   When i use the sdk with device have only back facing camera , the camera is not open.
  I try set camera type to default type. it's still not work.

  Do you have any solution for this issue ?

**Comment by eddieMicroblink** [comment]
Hello,
Could you please provide us some more details about the device you're using?
Since there is only one camera, it might actually be classified as frontside,
you can try changing the settings the following way:
https://blinkid.github.io/blinkid-android/com/microblink/uisettings/CameraSettings.Builder.html#setType-com.microblink.hardware.camera.CameraType-

**Comment by Rina2001** [comment]
I use wizarPOS Q2 device. I already set camera setting , But It seem like error like previous time.
The error : ` E/RecognizerRunnerView.java:501@Camera1: Exception caught on camera startup
    java.lang.RuntimeException: Fail to connect to camera service`.

**Comment by culoi** [comment]
Hi @Rina2001 

I suggest that you test with our DirectAPI sample that has a custom camera solution. 
https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DirectApiSample

Maybe this will resolve the issue with connecting to camera service.

Regards,

Ivan

**Comment by Rina2001** [comment]
Dear Ivan 
    Let me try run test with your sample API
Best regard,
Rina

**Comment by Rina2001** [comment]
Ok , it's worked, thank you.
