### ISSUE TITLE
blinkid scan ui can't open the camera view on some devices（ANR）

### ISSUE THREAD

**Issue by UnravelTheWorld** [BlinkID/blinkid-android#21]
my device info as shown below:
device name: xiaomi 5s
Android Version: 6.0.1
The screen resolution： 1920*1080  5.15 inches

Grab log is as follows：
[blinkid_logs.txt](https://github.com/BlinkID/blinkid-android/files/673697/blinkid_logs.txt)

**Comment by DoDoENT** [comment]
Please enable [verbose logging](https://github.com/BlinkID/blinkid-android#other-problems) and send us the entire log from starting up of camera activity. The log you sent is incomplete (i.e. everything logged in there is perfectly normal and does not indicate crash nor ANR).

**Comment by UnravelTheWorld** [comment]
there is a complete log（Include the system log）：
[blinkid_logs.txt](https://github.com/BlinkID/blinkid-android/files/674995/blinkid_logs.txt)

**Comment by UnravelTheWorld** [comment]
in addition,segment scan perfectly normal.there is screen shots:
![1](https://cloud.githubusercontent.com/assets/15966146/21513647/160b62d0-ccf6-11e6-9f85-654faadf4c39.png)
![Uploading 2.png…]()

>

**Comment by DoDoENT** [comment]
@UnravelTheWorld, the log you've sent now contains non-filtered logs from all apps, but still does not contain [verbose logging](https://github.com/BlinkID/blinkid-android#other-problems) from BlinkID SDK. You must enable verbose logging by adding this line

    com.microblink.util.Log.setLogLevel(com.microblink.util.Log.LogLevel.LOG_VERBOSE);

as a first line in your main activity's `onCreate` method. Since both segment scan and BlinkID use the same camera management code and since the camera error log is very similar to the one on OnePlus3, it is possible that both devices have same camera HW with same [bug](https://forums.oneplus.net/threads/photomath-issue.479863/#post-15518260).

Try starting the ScanCard activity several times - is screen black always or sometimes it works? Try the same with segment scan. Does sometimes screen also remains black on segment scan?
