### ISSUE TITLE
Option to set specification in MrtdCombinedRecognizer

### ISSUE THREAD

**Issue by ChethanYoti** [BlinkID/blinkid-android#222]
Hi Team,

With the `MrtdRecognizer`, we can set the specification to recognise only MRTD type3 documents with the help of `MRTD_SPECIFICATION_TD3`. But with the `MrtdCombinedRecognizer` we don't have  option to set such specification. In `MrtdCombinedRecognizer` is there any way to recognise only MRTD type3 document. If its not available it will be great if you provide an option to set the specification(like `setSpecifications` in `MrtdRecognizer`).

**Comment by mparadina** [comment]
Hi @ChethanYoti 

Can you please tell me which documents are you trying to scan?

Regards,
Milan

**Comment by ChethanYoti** [comment]
Passport

**Comment by mparadina** [comment]
Hi @ChethanYoti 

Our recommendation for scanning passports is using the BlinkID recognizer since we've added support for reading travel visas and passports from version 5.5. 
Or another option is using the PassportRecognizer.

The MRTD combined recognizer wasn't specifically designed for reading passports since the MRZ (on passports) is located on the front side. It was designed for documents which have MRZ on the backside, but you still require the image of the front side of the document.

Hope this helps.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @ChethanYoti 

Just following up on this thread.

Did you try using the BlinkID recognizer?
Did you get the expected results?

Regards,
Milan

**Comment by ChethanYoti** [comment]
Yeah..its working Milan:)
