### ISSUE TITLE
Is BlinkIdCombinedRecognizer able to set Scan Front Side Only?

### ISSUE THREAD

**Issue by ahshingx95** [BlinkID/blinkid-android#229]
Hi

I was trying to use BlinkIdCombinedRecognizer to scan Malaysia MyKad, it has both front and back side, and it works flawlessly. But I wanted to only Scan front side, is there an option to Scan Front Side Only, and skip scan Back Side? I tried using recognizer.setSkipUnsupportedBack(true); but I know this isn't the way. But I don't see any other option. Please advice.

Thanks and Regards,
Shing

**Comment by mparadina** [comment]
Hi @ahshingx95 

For one-side scanning, you can use the BlinkID recognizer (not the Combined recognizer).
This recognizer requires only one side of the supported document to extract the information, while the Combined recognizer requires scanning both sides of the document in order to extract the information.

You can see the differences between the recognizers here: 
https://github.com/BlinkID/blinkid-android#-blinkid-recognizer

BlinkID recognizer documentation: https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdRecognizer.html

Hope this helps. 
Feel free to ask in case of any additional questions.

Regards,
Milan

**Comment by ahshingx95** [comment]
> Hi @ahshingx95
> 
> For one-side scanning, you can use the BlinkID recognizer (not the Combined recognizer).
> This recognizer requires only one side of the supported document to extract the information, while the Combined recognizer requires scanning both sides of the document in order to extract the information.
> 
> You can see the differences between the recognizers here:
> https://github.com/BlinkID/blinkid-android#-blinkid-recognizer
> 
> BlinkID recognizer documentation: https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdRecognizer.html
> 
> Hope this helps.
> Feel free to ask in case of any additional questions.
> 
> Regards,
> Milan

Thanks a lot for guidance, it really helps! Much appreciated and thank you!
