### ISSUE TITLE
BLINKIDCOMBINEDRECOGNIZER showing null results after successful Scan

### ISSUE THREAD

**Issue by Robotrator** [BlinkID/blinkid-android#232]
Hello, I am trying to scan my National Card. in your provided sample code, it works absolutely fine and I get complete details of my card. Now when I tried to integrate the code with my application. Firstly there was an invalid license key exception, then I face in .mblic file of assets. But somehow I found the solutions from previously asked questions on this platform. 

Currently, the application is working fine, it scans the card and goes to the Results Screen where we can select Mixed/Front side OCR/Back side OCR etc. BUT it has not extracted any data. All the fields are empty, there is no Name/Address/Date of Birth etc. 

Could you please figure out, what's the wrong move I am doing? in Sample Application, all works fine. In my Application, all works but no results found.

com.microblink:blinkid:5.8.0@aar

**Comment by SandraKuzmic** [comment]
Hi @NumanGillani-jackys 

can You send us Your minimal sample app where we can reproduce this issue?

Best regards,
Sandra

**Comment by NumanGillani-jackys** [comment]
Yes sure, I'm sharing the WeTransfer Link of Source Code. Kindly go through this. This App I created for you, and found the same issue. Also it is taking some time to load camera, in your Github, camera opens so quickly

Also I don't want to Scan back side of Card, so just front side and that's enough. is that possible? How I can do this in below project?

https://we.tl/t-ytHR5IkY2m

**Comment by SandraKuzmic** [comment]
Hi @NumanGillani-jackys 

regarding scanning just one side, You could use [BlinkIdRecognizer](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdRecognizer.html) instead BlinkIdCombinedRecognizer.

Also, I checked the sample You sent, I did get results for scanning a couple of different documents, but they are not visible due to background/text color. Try changing the text color and let me know if it helped.

Best regards,
Sandra

**Comment by anjapenic** [comment]
Hello @Robotrator,

Since this issue is inactive for some time, we're closing it. If you need any further assistance, feel free to open a new one or contact us at support@microblink.com.

Best regards,
Anja
