### ISSUE TITLE
Picture quality

### ISSUE THREAD

**Issue by SimonRolin** [BlinkID/blinkid-android#233]
Hi,

We have implemented the latest version of blinkid and rollout our app in production about a week ago. Our use case is somehow special as a backend ocr is used after the mobile one. 
The quality of the picture received by the backend doesn't seem to be enough and I was wondering if it would be possible to get a better image quality ? 

I'm already setting the fullDocumentImageDpi to 400 and enableHighResSuccessFrameCapture to true.

Is there anything else I could do to improve the final quality of the eid picture ?

Thanks a lot in advance !

**Comment by matvidako** [comment]
Hi,

if you enable high res success frame capture you'll get image at maximum supported camera resolution.
Your problem might be that you are enabling it but not actually using the correct image.
You can check how to use high res images in our [images sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java).

**Comment by SimonRolin** [comment]
Thanks a lot for your reply @matvidako .

Could you tell me if there is an option to get the picture with a frame around the id card ?

Thanks in advance !

**Comment by matvidako** [comment]
Hi,

we don't support frame around the id card.

If you just need cropped document image, you can try increasing camera preview resolution to `VIDEO_RESOLUTION_2160p` or `VIDEO_RESOLUTION_MAX_AVAILABLE`, configured via `setCameraSettings` UISettings method.
Increasing preview resolution might cause performance issues on some devices but it will increase the quality of full document image.

The alternative is to do a regular scan with high res frame enabled and then run Direct API recognition on the high res frame.
Since high res frame is much higher resolution than preview frames, you'll get higher quality full document images.
You can check how to use Direct API in our [sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-DirectApiSample/src/main/java/com/microblink/blinkid/imagescan/CombinedScanImageActivity.java).
The problem with this approach is that Direct API can sometimes have trouble with recognition using just a single frame.

**Comment by SimonRolin** [comment]
Hi @matvidako ,

Thanks for your answer. Do you have a sample of using VIDEO_RESOLUTION_2160p or VIDEO_RESOLUTION_MAX_AVAILABLE ?

Also, we receive on our backend files like this one : 
![Front_Raw (4)](https://user-images.githubusercontent.com/5501874/99936682-fe83e100-2d63-11eb-8a3b-f12f3f80ecf6.jpeg)

How can we avoid this ? We are really not looking for speed, we only want to have eid card in the correct orientation, correctly cropped and which are still valid (and that we can parse on our backend OCR).

Once again, thanks in advance !

**Comment by matvidako** [comment]
Hi,

you can update preview resolution like this:
```
CameraSettings cameraSettings = new CameraSettings.Builder()
                .setVideoResolutionPreset(VideoResolutionPreset.VIDEO_RESOLUTION_2160p)
                .build();
uiSettings.setCameraSettings(cameraSettings);
```

As for the incorrect cropping, we're constantly working on improvements. It would be helpful if you also have full camera frame, so that we can check what could be causing the issue.
To get full camera frame, you can either enable high res frame, or wrap your recognizer inside `SuccessFrameGrabber`, you can see how to do both in our [images sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java).

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
