### ISSUE TITLE
Need the store-app like line animation in scan screen in BlinkID-CustomCombinedSample

### ISSUE THREAD

**Issue by samirpramanik** [BlinkID/blinkid-android#238]
### Description

I am using BlinkID-CustomCombinedSample project and wish to customize the overlay with a scan animation that is similar to the one that is used in your store app BlinkID(the blue line animator). So, is there any component that I can reuse in my custom activities to have the same look and feel over the recognizer or do I have to create these on my own?

### Environment Details

**BlinkID version:**
5.9.0

**Comment by mparadina** [comment]
Hi @samirpramanik 

Thank you for waiting for our response.

Regarding the UI used in the BlinkID demo application, it is called the [BlinkID UI](https://github.com/BlinkID/blinkid-ui-android).

However, it has been deprecated since we used to have document-specific recognizers so the BlinkID UI helped you set them up correctly. 
In version 5 we have one recognizer, BlinkID (Combined) Recognizer, that can be used to scan all documents that we support.

Would you mind explaining why do you need the BlinkID UI components? 

Regards,
Milan

**Comment by samirpramanik** [comment]
Hi @mparadina 

Actually my current production app has the same UI as BlinkID UI, and I wish to continue with the same UI for consistency. Therefore, is there any way to achieve this with the latest Blink ID sdk? Any overlay or layout file that can be customized for the same look and feel as Blink ID UI?

Regards,
Samir

**Comment by mparadina** [comment]
Hi @samirpramanik 

Thank you for waiting for our response.

If your use-case only considers using the BlinkID UI, this UI is open-source, so you can adjust it to your needs and replace the country-specific recognizers with the BlinkID/BlinkID Combined recognizer.
 
You can find the BlinkID UI here:
https://github.com/BlinkID/blinkid-ui-android

However, as I've mentioned in my previous response, we recommend using the BlinkID overlay which comes with version 5 since it best suited for the BlinkID and BlinkID Combined recognizers.

Regards,
Milan

**Comment by samirpramanik** [comment]
Thank you.
