### ISSUE TITLE
ImageListener implementation 

### ISSUE THREAD

**Issue by k0shk0sh** [BlinkID/blinkid-android#24]
May i know if there is anyway that can actually return the full scanned image without using the ImageListener? It's so problematic and its not even recommended that you pass interfaces along side the intent to be able to receive the image, as you are keeping a strong reference of the whole object within your activity & what is even worse, for ex: we will never get the data from listener if for ex: we started the ScanActivity & then rotated the device we trigger a configuration changes which now destroys the interface class that is being implemented by another class since we really don't want you to hold on a reference to the activity that is starting the intent.
Is there anyway to get around this besides creating our own ScanActivity & without keeping a strong reference to the interface(ImageListener class)? if there is no such way right now. are you planning to improve on this process by simplifying it to lets say returning the image if one actually request for it in one of the intent exteras ?

**Comment by culoi** [comment]
Hello k0shk0sh 
You can use [Metadata listener](https://github.com/blinkid/blinkid-android#metadataListener) in your [custom scan activity](https://github.com/blinkid/blinkid-android#recognizerView). If you want to use our own ScanActivity, then there is no other way to send image except via ImageListener. The reason for this is the Android API limit: there is a limit of 64 kB of data that can be sent via Intent, and this is not enough to transfer image, even if we encode it to JPEG and degrade its quality a lot. Since our SDK cannot access SD card either, we also can’t sent image back by saving it to file and sending the file path back. So, from our perspective it’s best to give you the opportunity to implement the ImageListener interface, obtain the image and send it to your app back via any method that suits you best.
For configuration changes problem - you should [never allow restarts of activity that manages camera](https://github.com/blinkid/blinkid-android#-scan-activitys-orientation), as this will cause problems with your device. The recommended way is to allow config changes which, instead of restarting the activity, call _onOrientationChange_, or even better, you can simply leav default ScanActivity always in portrait - it will internally handle orientation changes for UI other than camera preview surface.

**Comment by mvayngrib** [comment]
@culoi @k0shk0sh you can also use a singleton class to store images in onImageAvailable, and pick them up in onActivityResult

**Comment by k0shk0sh** [comment]
@culoi  The camera activity isn't the activity that is being recreated, its out activity that starts the scanActivity, even when the activity is set to not be recreated the `imageListener` will always be null when returning result from the `ScanActivity`, as @mvayngrib suggested, one of the ways to workaround this is to have a singleton class or defining the image patch in the activity and pass it to the `ImageListener` to process saving it.

**Comment by Cerovec** [comment]
Hi @k0shk0sh,
is this still an open issue to you?
Can we help you somehow else?
Thanks,
Jurica.

**Comment by k0shk0sh** [comment]
@Cerovec I guess this issue can be closed. Thanks

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shobhan1595** [comment]
Even I am facing the same issue  , When I have added the image listener , Does any body resolved this issue ? Please let me know your solution

**Comment by DoDoENT** [comment]
Hi @shobhan1595, the solution is to create [custom scanning UI](https://github.com/BlinkID/blinkid-android#recognizerView) and to use [MetadataListener](https://github.com/BlinkID/blinkid-android#metadataListener) instead.
