### ISSUE TITLE
Extract information from Address

### ISSUE THREAD

**Issue by souheib93** [BlinkID/blinkid-android#241]
I want to extract information from Address such as : 

- Street
- House Number
- Zip Code
- City

Is there any possibility to do that ?

BlinkIdCombinedRecognizer.Result offer that the full address

Thank you for your help

**Comment by mparadina** [comment]
Hi @souheib93 

Thank you for waiting for our response.

Currently, with the BlinkID recognizer, we return the address field as one piece of information which contains all of the information you've mentioned above.
In order to separately extract the mentioned information, you would need to use your own parsing logic.

Just to double-check, which documents are you scanning?

Let me know if you have any additional questions.

Regards,
Milan

**Comment by souheib93** [comment]
Hi @mparadina  

Thank you for your reply.

I am scanning various documents, then we will have different addresses format
that's why i asked if you offer that.

Thank you for the information

**Comment by mparadina** [comment]
Hi @souheib93 

Yes, as mentioned before, all of the address information that gets scanned and extracted can be returned with the [getAddress](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdRecognizer.Result.html#getAddress--) method in the BlinkID's result.

Depending on the scanned document, the information returned in the results (for instance, the city and ZIP code) is separated via commas, making it easier to parse.

Let me know if you have any additional questions.

Regards,
Milan

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
