### ISSUE TITLE
offline support (private network)

### ISSUE THREAD

**Issue by Elswah** [BlinkID/blinkid-android#250]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

get dialog network error while using lib on private network
how to solve this problem

### Environment Details

**BlinkID version:** 5.11

**Device Android version:** 5.0.1

**Comment by anjapenic** [comment]
Hello @Elswah,

The SDK requires an internet connection in order to properly work in order to validate whether or not the entered license key is valid. It communicates with our server in order to check its validity. 

Keep in mind that the SDK only needs an internet connection to check if the license key is valid. The document information extraction still happens offline, on the device itself.

Once the license key validation is complete, you can continue using the SDK in offline mode (or over a private network).

Best regards,
Anja

**Comment by Elswah** [comment]
i'm searching for completely offline solution ,also after purchase licence i will not connect to internet
did you have any solution for my case
thanks

**Comment by anjapenic** [comment]
Hi @Elswah,

Could you please contact our Sales team at sales@microblink.com? They can offer you more info on the possibility of a completely offline solution.

Best regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
