### ISSUE TITLE
BlinkCardRecognizer & BlinkCardActivity are not found!

### ISSUE THREAD

**Issue by EhabSalah** [BlinkID/blinkid-android#267]
How to scan credit card through this SDK?!

>BlinkCardRecognizer & BlinkCardActivity are not found!

**Comment by MBrizic01** [comment]
Hi, EhabSalah, thank you for reaching out! 
BlinkID is an SDK that is used for scanning and extracting information from identity documents, whilst BlinkCard SDK enables you to perform scans of various credit or payment cards in your app.

As you posted your question under the BlinkID thread I just wanted to clarify that you can’t scan credit cards using this SDK.
 If you need both of them, you can combine them in the same application as explained [here](https://help.microblink.com/s/direct-article?Article=ka05e000001k4V6AAI). Otherwise, you can proceed with only BlinkCard integration, following [these steps](https://github.com/blinkcard/blinkcard-android#intro).
