### ISSUE TITLE
Library size is huge

### ISSUE THREAD

**Issue by k0shk0sh** [BlinkID/blinkid-android#3]
are there any plans to reduce the lib size? my testing app wish uses proguard jumps from 5MB to 18MB when i added your library. P.S: im using the proguard configs you provided.

**Comment by DoDoENT** [comment]
Hi, BlinkID is native library and native code is rather large because it needs to be compiled separately for each supported Android ABI.

You can reduce the size of your app by following [our app size reducing guidelines](https://github.com/BlinkID/blinkid-android#reduceSize).

**Comment by k0shk0sh** [comment]
this isn't a good option for us, as we are not deploying the apk to the playstore. any other solutions?

**Comment by DoDoENT** [comment]
There is still one possible solution: in your app's build.gradle under android section, add following statement:

    packagingOptions {
        exclude 'lib/arm64-v8a/libBlinkID.so'
        exclude 'lib/x86/libBlinkID.so'
        exclude 'lib/x86_64/libBlinkID.so'
    }

You can't reduce your app more than that. **Note:** this will remove support for Intel devices completely and on ARM64 devices (like SGS6, Nexus 5X and most new devices) performance will not be optimal due to using ARM7 binary in emulation mode.

**Comment by DoDoENT** [comment]
Hi @k0shk0sh,

can we close this issue?

**Comment by DoDoENT** [comment]
I would just like to add that new release has more detailed documentation on reducing application size by eliminating CPU ABIs that are not required. You can check it [here](https://github.com/BlinkID/blinkid-android#removing-processor-architecture-support-in-gradle-without-using-apk-splits).

**Comment by k0shk0sh** [comment]
Please go ahead, thanks
