### ISSUE TITLE
RegexParserSettings - Issues with positive lookbehind

### ISSUE THREAD

**Issue by CattleOfRa** [BlinkID/blinkid-android#43]
Microblink seems to have some issues dealing with positive lookbehinds and lookaheads. Simple regex queries like the following work marvelously:

`RegexParserSettings parser = new RegexParserSettings("([A-Z]+ ?)+");`

Whilst something like:

`RegexParserSettings parser = new RegexParserSettings("(?<=: )([A-Z]+ ?)+");`

Will cause the application to crash with the following error:

> A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20 in tid 17527

Sample text to process: 

> : ABC DEF

Essentially I am trying to get the 'ABC DEF' from the card, the text must include the colon but without grouping it, so when I return the results it won't have the colon in there, only the text will be parsed to the OCR results.

Update 1:

Same problem happens with non capturing groups and "." (any characters).

Such as the following example:

`RegexParserSettings parser = new RegexParserSettings("(0?[1-9]|[12][0-9]|3[01]).(0?[1-9]|1[012]).\\d{4}");`

**Comment by DoDoENT** [comment]
Hello!

Thank you for your report. As [documented](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/parser/regex/RegexParserSettings.html#setRegex-java.lang.String-), back references (i.e. capture groups) are not supported by our regex engine. 

Also, '.' meta-character that represents any character and '^' inside brackets representing all characters except those in brackets are available only if alphabet is defined, i.e. only if you have also defined a character whitelist in [BlinkOcrEngineOptions](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/engine/BlinkOCREngineOptions.html).

However, the crash you are experiencing is definitely a bug in SDK.

More info: due to requirement to parse a OCR result, not a string, we need to perform custom regex matching logic and therefore cannot use third-party off-the-shelf regex engines which do not provide the flexibility we need (such as support for handling common OCR mistakes etc.). Our custom regex matching logic is not on par with most regular expression engines and works only with rather simple expressions.

Nevertheless, we will try to reproduce your crash and hopefully fix it.

**Comment by CattleOfRa** [comment]
Hi there,

Thank you very much for clarifying this issue.

So currently I am using the following code to read blood type from an ID:

`parser.setRegex(":\\s?([ABO]{1,2}[+-]?)");`

Obviously though, this is not the most accurate regex for blood type, ideally I would like to have:

`:\s?[AB][^O][AB]?[+-]?|:\s?[O][^AB][+-]?)`

But this is not possible because it does not fit this criteria: _'^' inside brackets representing all characters except those in brackets are available only if alphabet is defined_

Nevertheless, the code which works cannot be set during the initialization of the object (RegexParserSettings), so my work around is to set the regex to an empty string and set it using parser.setRegex(...);

```
RegexParserSettings parser = new RegexParserSettings("");
BlinkOCREngineOptions boeo = new BlinkOCREngineOptions();
BlinkOCRCharKey keyColon = new BlinkOCRCharKey((int)':', OcrFont.OCR_FONT_ANY);
BlinkOCRCharKey keyA = new BlinkOCRCharKey((int)'A', OcrFont.OCR_FONT_ANY);
BlinkOCRCharKey keyB = new BlinkOCRCharKey((int)'B', OcrFont.OCR_FONT_ANY);
BlinkOCRCharKey keyO = new BlinkOCRCharKey((int)'O', OcrFont.OCR_FONT_ANY);
BlinkOCRCharKey keyMinus = new BlinkOCRCharKey((int)'-', OcrFont.OCR_FONT_ANY);
BlinkOCRCharKey keyPlus = new BlinkOCRCharKey((int)'+', OcrFont.OCR_FONT_ANY);
boeo.addCharToWhitelist(keyColon);
boeo.addCharToWhitelist(keyA);
boeo.addCharToWhitelist(keyB);
boeo.addCharToWhitelist(keyO);
boeo.addCharToWhitelist(keyMinus);
boeo.addCharToWhitelist(keyPlus);
parser.setOcrEngineOptions(boeo);
parser.setRegex(":\\s?([ABO]{1,2}[+-]?)");
```

During the initialisation of the Regex it complaints about the list of characters being empty, so this was my way around it

**Comment by DoDoENT** [comment]
Your workaround is OK, but it would be easier for you to use [constructor that accepts both regular expression and engine options](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/parser/regex/RegexParserSettings.html#RegexParserSettings-java.lang.String-com.microblink.recognizers.blinkocr.engine.BlinkOCREngineOptions-) which is intended for use cases like yours.

**Comment by CattleOfRa** [comment]
Works like a charm!

Thank you very much for the help.
