### ISSUE TITLE
How to Scan ID of Nigerian Driving License?

### ISSUE THREAD

**Issue by karanaggarwal1** [BlinkID/blinkid-android#46]
I am looking to pull the details from the front of the Nigerian DL using Templating API. So far I have made the menuActivity, and the Templating Class from which I will get the settings as well.
![whatsapp image 2017-07-07 at 3 54 12 pm](https://user-images.githubusercontent.com/25701626/27998172-45888cfe-6526-11e7-9b12-67f1b5492670.jpeg)
Here is a sample of the front of the Nigerian DL. I have made the appropriate dimensions as well but I am getting a log like this:
07-10 03:56:49.340 1871-4271/package name W/TemplatingRecognitionData.cpp:107: Required parser 'DocumentNumber' from parser group 'DocumentNumber' did not produce result!
Please help ASAP

**Comment by DoDoENT** [comment]
Hello!

The message `Required parser '<parserName>' from parser group '<parserGroup>' did not produce result!` simply informs you that on current video frame specified parser in specified parser group failed to extract information from OCR result. This could be due to poor detection, poor light conditions, bad quality device camera or due to decoding info for given parser group being positioned in the wrong place, so that image part that is being OCRed does not contain whole information that needs to be extracted.

For detailed tutorial how Templating API should be used, please check [this link](https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md) which is accompanied by [these code examples](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemo/src/main/java/com/microblink/util/templating).

If you want to visualise the images that are being OCRed, with purpose to help you better position the crop locations, you can install [listener which can receive images that are being OCRed](https://github.com/BlinkID/blinkid-android#imageListener) and enable receiving of [debug dewarped images](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.ImageMetadataSettings.DebugImageMetadataSettings.html#setDewarpedImageEnabled-boolean-) in [debug image metadata settings](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.ImageMetadataSettings.html#setDebugImageMetadataSettings-com.microblink.metadata.MetadataSettings.ImageMetadataSettings.DebugImageMetadataSettings-).

**Comment by culoi** [comment]
Closing the issue, please reopen if you have questions or contact us directly at support@microblink.com.
