### ISSUE TITLE
RandomScanActivity Issue

### ISSUE THREAD

**Issue by raja-mukherjee** [BlinkID/blinkid-android#50]
Intent intent = new Intent(this, RandomScanActivity.class);
        intent.putExtra(RandomScanActivity.EXTRAS_LICENSE_KEY, Config.LICENSE_KEY);

        RandomScanElement[] elemsArray = new RandomScanElement[] {
                new RandomScanElement(R.string.name_title, NAME_PARSER, new RawParserSettings()),
                new RandomScanElement(R.string.number_title, NUMBER_PARSER_NAME, new RawParserSettings()),
                new RandomScanElement(R.string.address_title, ADDRESS_PARSER_NAME, new RawParserSettings())};
        
        intent.putExtra(RandomScanActivity.EXTRAS_SCAN_CONFIGURATION, elemsArray);
        intent.putExtra(RandomScanActivity.EXTRAS_BEEP_RESOURCE, R.raw.beep);
        startActivityForResult(intent, SINGLE_REQ_CODE);

I am trying to perform ocr on Indian Adhar card using this block of code. While camera preview is running, I can see 3 text box to populate data. After completion of 1st box , ocr engine , instead of populationg data to the 2nd textbox, it is trying to override the first one. Am i missing any flag?

**Comment by lirfu** [comment]
Hi @raja-mukherjee,

you're calling the `RandomScanActivity` with 3 parsers of the same type. 

The `RandomScanActivity` was intended to read data without an order (hence the name 'random') so it needs to somehow associate the scanned inputs with the given parsers. Furthermore, on every input instead of trying other parsers it'll rather update the first one to improve it's readout quality. 

Because of that it requires a parser configuration that is mutually excludable, in other words there must not be two or more parsers that read the same type of data.

In your case, you should use the `SegmentScanActivity` instead and for each readout you'll be asked to accept what it read and move on to the next field. Here are the `SegmentScanActivity` [code sample](https://github.com/BlinkID/blinkid-android#-performing-your-first-segment-scan) and [further customization instructions](https://github.com/BlinkID/blinkid-android#-customization-of-segmentscanactivity-activity).

**Comment by raja-mukherjee** [comment]
Thanku for your quick response.
