### ISSUE TITLE
How to scan the ID card and driver licence in Mexico

### ISSUE THREAD

**Issue by pmbfish40** [BlinkID/blinkid-android#51]

**Comment by i1E** [comment]
Hi @pmbfish40,

Scanning Mexico driver's license is not supported yet by the SDK. You can scan the back side of the ID card which contains MRZ (*Machine Readable Zone*) by using [MRTDRecognizer](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognizerSettings.html), you can find more information in [this](https://github.com/BlinkID/blinkid-android#-scanning-machine-readable-travel-documents) documentation section. Code example is available in the [demo app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDDemo/BlinkIDDemo/src/main/java/com/microblink/blinkid/MenuActivity.java#L336). 

In order to improve support for Mexican documents in the future, we need more examples. We will be very grateful to you if you can send us some document samples to support@microblink.com.

**Comment by pmbfish40** [comment]
Hi there. 

Why I should scan only back side? What about the front side

**Comment by i1E** [comment]
Mexican ID card and Driver's license are not supported out of the box by BlinkID SDK. [MRTDRecognizer](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognizerSettings.html) scans only data contained in the MRZ (*Machine Readable Zone*). I suppose that back side of Mexican ID card contains the MRZ, that is why I wrote that you can scan back side with the MRTDRecognizer. 

You can use Templating API to build support for scanning your own document type. You can find more information about Templating API [here](https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md). Also you can try our [demo app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemo) with Templating API example for [front](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDDemo/BlinkIDDemo/src/main/java/com/microblink/util/templating/CroatianIDFrontSide.java) and [back](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDDemo/BlinkIDDemo/src/main/java/com/microblink/util/templating/CroatianIDBackSide.java) side of Croatian ID card.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have questions or contact us directly at support@microblink.com.
