### ISSUE TITLE
Unable to install library in Android studio 3.0

### ISSUE THREAD

**Issue by dpondeljak** [BlinkID/blinkid-android#63]
Hello 

I have issue with installing LibBlinkID library in my project 

I followed instructions which you provided but i've got this error 

**Error:Configuration with name 'default' not found.**

what should i do to solve this .

thanks in advance 
regards

**Comment by DoDoENT** [comment]
Hello! Since Android Studio 3.0 and gradle plugin 3.0 were moved to stable channel yesterday, we still haven't updated our documentation and demo apps for changes in new gradle plugin that are described [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html). At the moment we recommend using the [maven integration approach](https://github.com/BlinkID/blinkid-android#-integrating-blinkid-into-your-project-using-maven) which should work with gradle plugin 3.0.

If that is also giving you problems, then I'll recommend sticking with gradle plugin 2.3.3 (which can still be used in AS 3.0) until we officially update our documentation and demo apps for gradle plugin 3.0.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have questions or contact us directly at support@microblink.com.
