### ISSUE TITLE
German Id Back Side is not recognizing

### ISSUE THREAD

**Issue by iravul** [BlinkID/blinkid-android#83]
I am using GermanIDBackSideRecognizerSettings to detect German ID's back side and getting Issue Date and Authority. But it does not detect. Even with using BlinkIdSample project demo application. In the logs i saw this message:

`TemplatingRecognizer.cpp:179: Cannot find parser group for location 'MRTD_TD1'. Will not perform OCR and parsing of that location!`

I am using 3.15.1

**Comment by iravul** [comment]
Hi @culoi ,

I just observed that, if Back of ID has Address sticker, it is not recognising. If there is no address sticker in backside, it always working well. 

But problem is, in Germany most of people has this sticker, because government put this sticker for every address changing of person. Is there any way to scan with that sticker?

You can check sample sticker in here: https://image.ibb.co/j4kohn/Screen_Shot_2018_03_05_at_13_06_43.png

Thank you

**Comment by culoi** [comment]
Hi @iravul 

The problem is to figure out the area of the sticker and adjust the way to read information from it. Letters are much smaller and we have a low contrast which is never good for the detection.
The idea was that if there is a sticker in the upper right corner, we need to detect it somehow.

On sticker, there is a document number, and if we detect it, then we know that we have a sticker and we can adjust to it.
The problem is that this document number is often covered with a stamp and it is not possible to detect if we have an ID with the sticker with our current OCR model.

We did not really dedicate time to this problem because we did not have enough examples. 

Now that we have an adequate number of examples, we should see if something can be done with our current OCR model if not, then I hope we can sort it out when we finish refactor and use a deep document classifier that would hopefully be able to distinguish whether or not we have a label

We can continue this discussion over email, please contact us at support@microblink.com.

Regards
