### ISSUE TITLE
Get Card Side

### ISSUE THREAD

**Issue by h777arsh** [BlinkID/blinkid-android#84]
Hi,

I'm currently using `CombinedRecognizerSettings` for US Driving license. One issue I'm facing currently is that when we start scanning for front side and user scan back side of the card and then we can not scan backside again.  so anything to prevent that scenario? 

Thanks.

**Comment by DoDoENT** [comment]
Hi @h777arsh!

In order for scanning both front and back side of US Driving License, I suggest using [USDL Combined recognizer](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/usdl/combined/USDLCombinedRecognizerSettings.html). This recognizer will first expect user to scan the front side of the US document and after front side is scanned, the user must then turn the document so the back side can be scanned. The recognizer scans the PDF417 barcode from the back side and only captures the image of the document on the front side.

Due to the way it works, it may be possible that if the user first presents the back side that front side recognition code could mis-recognize the back side as front side, however this should be rare and is considered a bug. Even in this case, the barcode from the back side should be scanned without any problems.

To help your user to correctly position the correct side of the document while scanning, you should create a good scanning UI that guides the user through the process. An example of such UI is used within our [verification flow activity](https://blinkid.github.io/blinkid-android/com/microblink/activity/VerificationFlowActivity.html) which is designed for scanning front and back side of documents using combined recognizers. If you want to create your own scanning UI based on ideas from that activity, you can take a look at [this sample app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDCustomCombinedSample).

**Comment by h777arsh** [comment]
Hi @DoDoENT,

Thanks for quick reply. 

I'm using USDL Combined recognizer and you are right about some kind of small tutorial that will help the user. and still, user scanned backside first then we can nothing about that right?

**Comment by DoDoENT** [comment]
> and still, user scanned backside first then we can nothing about that right?

At the moment no, because first side of USDL scanning reduces to using [Document Face Recognizer](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/documentface/DocumentFaceRecognizerSettings.html), which is not very clever - it takes the picture as soon as it detects a face within a card-like document. It's easy to confuse it.

We plan to add full support for reading front side of USDL in the future and then front side document recognition should not scan the back side by accident.
