### ISSUE TITLE
How to add the background image for the recognizer view 

### ISSUE THREAD

**Issue by harishmedamoni** [BlinkID/blinkid-android#96]
Hi Team,

We are using blink id 3.12.0 version of blink id for android.
We are scanning the passport and want to apply a background image for the recognizer view.

We are using a custom scan activity with  com.microblink.view.recognition.RecognizerView 

Below is my custom scan activity layout xml
----------------------------------------------

<FrameLayout    android:id="@+id/my_scan_root"
                xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                xmlns:custom="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent"

                tools:context="com.microblink.blinkid.demo.customui.MyScanActivity">

    <com.microblink.view.recognition.RecognizerView
        android:id="@+id/recognizerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/ei_back"
        custom:mb_initialOrientation="landscapeRight"
        >

    </com.microblink.view.recognition.RecognizerView>

I tried to apply background image for the recognizer view, but it is not displayed
Note:  ei_back is my drawable
 
Please help.

Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by DoDoENT** [comment]
Hi @harishmedamoni!

RecognizerView is basically a FrameLayout which contains three views - a surface view containing canvas where camera preview is being displayed, a FrameLayout for hosting _non-rotatable_ views on top of camera preview and a special version of FrameLayout for hosting _rotatable_ views on top of camera preview. For more information about this, check [this article](https://github.com/BlinkID/blinkid-android#-scan-activitys-orientation).

If you want to display image background, you should simply use some standard view with background and put RecognizerView on top of it. But bear in mind that this background will almost never be visible because camera surface view is opaque.

What use case are you trying to solve with your background image?
